[program:play31-app]
directory=/root/game
command=/bin/bash scripts/run_app.sh
autostart=false
autorestart=false
startsecs=3
stopasgroup=true
killasgroup=true
stdout_logfile=/root/game/data/app.log
stderr_logfile=/root/game/data/app.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
redirect_stderr=true

[program:play31-tunnel]
directory=/root/game
command=/bin/bash scripts/run_tunnel.sh
autostart=false
autorestart=false
startsecs=3
startretries=10
stopasgroup=true
killasgroup=true
stdout_logfile=/root/game/data/tunnel.log
stderr_logfile=/root/game/data/tunnel.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
redirect_stderr=true
